"""Generate tests/analytic_pearson_fixtures/mod.rs from scanpy's reference.

The count matrix is rebuilt from the same seeded Numerical Recipes LCG the
scTransform fixture uses, on both sides, so nothing but integers and the
reference answers crosses as text.

Two groups are emitted as well as the pooled case. The second half of the cells
is thinned to a third of its counts, so the two samples have genuinely
different sequencing depths and a pooled model is wrong for both. That is the
whole point of the per-sample path.

The reference is `scanpy.experimental.pp._normalization._pearson_residuals`,
which is the closed form of Lause, Berens & Kobak (Genome Biology 2021) Eq. 12:
`mu = outer(cell sums, gene sums) / total`, residuals clipped to `+/- sqrt(n)`,
`theta = 100`. The residual *variance* is reduced from that matrix here with
numpy rather than taken from `highly_variable_genes`, because scanpy's HVG path
divides by `n` while this crate, like sctransform, divides by `n - 1`. Both are
emitted so the relationship is pinned rather than assumed.

Run from the repo root:
  uv run --python 3.11 --with scanpy python dev/gen_analytic_pearson_fixtures.py \
      > tests/analytic_pearson_fixtures/mod.rs
  rustfmt --edition 2024 tests/analytic_pearson_fixtures/mod.rs
"""

import numpy as np
import scanpy as sc
from scanpy.experimental.pp._normalization import _pearson_residuals

LCG_SEED = 20260101
N_GENES = 300
N_CELLS = 400
MIN_CELLS = 5
THETA = 100.0
# Cells at or above this index form the second, thinned sample.
SPLIT = N_CELLS // 2
# Divisor applied to the second sample's counts.
THIN = 3

_state = LCG_SEED


def lcg_unif() -> float:
    global _state
    _state = (1664525 * _state + 1013904223) % 4294967296
    return _state / 4294967296


lib_scale = np.array([2000 + 6000 * lcg_unif() for _ in range(N_CELLS)])
gene_rate = np.array([10 ** (-5 + 3.2 * lcg_unif()) for _ in range(N_GENES)])

# Gene-major, exactly the draw order the R generator and the Rust side use.
counts = np.zeros((N_GENES, N_CELLS), dtype=np.int64)
for g in range(N_GENES):
    for c in range(N_CELLS):
        u = lcg_unif()
        counts[g, c] = int(np.floor(u * u * u * gene_rate[g] * lib_scale[c] * 12))

# The thinning is integer division, which the Rust side mirrors exactly.
counts[:, SPLIT:] //= THIN


def fixture_for(cell_slice: slice) -> dict:
    """Retained genes, residual variances and probe residuals for one group.

    Two clip ranges are emitted per group. scanpy's default resolves against
    the cells it was handed, so a 200-cell sample clips at sqrt(200); the
    crate's grouped path deliberately shares one range across samples, resolved
    against the total cell count, so that residuals from a small sample are not
    squeezed harder than those from a large one and the two stay comparable
    when they land side by side in PCA. Both are pinned.
    """
    block = counts[:, cell_slice]
    detected = (block > 0).sum(axis=1)
    retained = np.flatnonzero(detected >= MIN_CELLS)

    # scanpy takes cells-by-genes and computes the marginals over whatever it
    # is given, so the filter has to be applied before the call, not after.
    x = block[retained, :].T.astype(np.float64)
    residuals = _pearson_residuals(x, theta=THETA, clip=None, check_values=False)
    shared = _pearson_residuals(
        x, theta=THETA, clip=np.sqrt(N_CELLS), check_values=False
    )

    return {
        "retained": retained,
        "gene_sums": x.sum(axis=0),
        "total": float(x.sum()),
        "cell_totals": x.sum(axis=1),
        # n - 1, matching sctransform's rowVars and this crate.
        "var_n_minus_1": residuals.var(axis=0, ddof=1),
        # n, matching scanpy's own highly_variable_genes.
        "var_n": residuals.var(axis=0, ddof=0),
        # The crate's grouped path: one clip range across every sample.
        "var_shared_clip": shared.var(axis=0, ddof=1),
        "residuals": residuals,
    }


pooled = fixture_for(slice(None))
group_a = fixture_for(slice(0, SPLIT))
group_b = fixture_for(slice(SPLIT, N_CELLS))

out: list[str] = []


def emit_usize_array(name: str, doc: str, values) -> None:
    body = ", ".join(str(int(v)) for v in values)
    out.append(f"/// {doc}")
    out.append(f"pub const {name}: [usize; {len(values)}] = [{body}];")
    out.append("")


def emit_f64_array(name: str, doc: str, values) -> None:
    body = ", ".join(f"{float(v):.17e}" for v in values)
    out.append(f"/// {doc}")
    out.append(f"pub const {name}: [f64; {len(values)}] = [{body}];")
    out.append("")


out.append(f"//! Generated by `dev/gen_analytic_pearson_fixtures.py`. Do not edit by hand.")
out.append("//!")
out.append(f"//! scanpy {sc.__version__}, numpy {np.__version__}.")
out.append("//!")
out.append("//! The counts are rebuilt from the LCG below rather than stored, so nothing")
out.append("//! but integers and reference answers crosses as text.")
out.append("")
out.append("#![allow(clippy::excessive_precision)]")
out.append("#![allow(clippy::approx_constant)]")
out.append("#![allow(dead_code)]")
out.append("")
out.append("/// LCG seed shared with the generator.")
out.append(f"pub const LCG_SEED: u64 = {LCG_SEED};")
out.append("/// Genes in the generated matrix.")
out.append(f"pub const N_GENES: usize = {N_GENES};")
out.append("/// Cells in the generated matrix.")
out.append(f"pub const N_CELLS: usize = {N_CELLS};")
out.append("/// First cell of the second, thinned sample.")
out.append(f"pub const SPLIT: usize = {SPLIT};")
out.append("/// Divisor applied to the second sample's counts.")
out.append(f"pub const THIN: u32 = {THIN};")
out.append("/// `min_cells` the reference ran with.")
out.append(f"pub const MIN_CELLS: usize = {MIN_CELLS};")
out.append("/// Shared overdispersion the reference ran with.")
out.append(f"pub const THETA: f64 = {THETA:.17e};")
out.append("")

for label, fx in (("POOLED", pooled), ("A", group_a), ("B", group_b)):
    emit_usize_array(
        f"{label}_RETAINED",
        f"Store indices of the genes passing `min_cells` in group {label}.",
        fx["retained"],
    )
    emit_f64_array(
        f"{label}_GENE_SUMS",
        f"Column sums over the retained block of group {label}.",
        fx["gene_sums"],
    )
    out.append(f"/// Grand total over the retained block of group {label}.")
    out.append(f"pub const {label}_TOTAL: f64 = {fx['total']:.17e};")
    out.append("")
    emit_f64_array(
        f"{label}_RESIDUAL_VARIANCE",
        f"Residual variance per retained gene in group {label}, `n - 1` denominator.",
        fx["var_n_minus_1"],
    )
    emit_f64_array(
        f"{label}_RESIDUAL_VARIANCE_N",
        f"The same, with scanpy's own `n` denominator.",
        fx["var_n"],
    )
    emit_f64_array(
        f"{label}_RESIDUAL_VARIANCE_SHARED_CLIP",
        f"Group {label} clipped at sqrt(N_CELLS) rather than its own cell count, "
        f"which is what the crate's grouped path does.",
        fx["var_shared_clip"],
    )

# A handful of individual residuals, so a variance that happens to agree cannot
# hide a row that does not.
PROBE_GENES = [0, 17, 100, len(pooled["retained"]) - 1]
PROBE_CELLS = [0, 1, 199, 200, 399]
out.append("/// Positions within the pooled retained gene set that PROBE_RESIDUALS covers.")
out.append(f"pub const PROBE_GENES: [usize; {len(PROBE_GENES)}] = {PROBE_GENES};")
out.append("/// Cell positions that PROBE_RESIDUALS covers.")
out.append(f"pub const PROBE_CELLS: [usize; {len(PROBE_CELLS)}] = {PROBE_CELLS};")
out.append("")
probe = [pooled["residuals"][c, g] for g in PROBE_GENES for c in PROBE_CELLS]
emit_f64_array(
    "PROBE_RESIDUALS",
    "Pooled residuals at PROBE_GENES x PROBE_CELLS, gene-major.",
    probe,
)

print("\n".join(out))
