//! Parity of the blitzGSEA implementation against the Python reference.
//!
//! Fixtures in `blitzgsea_fixtures/mod.rs` are generated by calling the
//! reference itself; `blitzgsea_fixtures/gen_fixtures.py` regenerates them.
//!
//! ### What can and cannot be compared exactly
//!
//! The enrichment score, the leading edge and the mapping from a score to a
//! p-value are all deterministic, so those are gated to floating point
//! tolerance. The calibration is not: the reference seeds Python's `random` but
//! draws its permutations through `numpy.random`, so its per-anchor samples are
//! not controlled by the seed it is given and cannot be reproduced from outside
//! Python. That half is compared statistically instead.
//!
//! The signature crosses as an integer LCG rather than as float data, and every
//! step from the LCG state to a signature value is exactly representable, so
//! both sides work from bit-identical inputs.

use approx::assert_relative_eq;

use bixverse_rs::core::math::stats::fit_gamma_mle;
use bixverse_rs::enrichment::blitzgsea::{
    BlitzGseaNull, BlitzGseaParams, BlitzGseaTail, blitzgsea_score, calibrate_null, pval_and_nes,
};

mod blitzgsea_fixtures;
use blitzgsea_fixtures::*;

////////////
// Consts //
////////////

/// Tolerance for quantities that are algebraically identical on both sides.
///
/// Not exact equality: the reference accumulates its enrichment score with a
/// full-length `numpy.cumsum` over every gene where this one sums only over the
/// hits, so the two drift by a few units in the last place. The reference's own
/// `bottom_50` score comes back as -1.0000000000000286 for that reason.
const EXACT_TOL: f64 = 1e-9;

/// Tolerance for the calibrated gamma shape.
///
/// Each quantity gets its own gate, set just above what is actually observed,
/// because a single shared tolerance loose enough for the shape would let the
/// scale and the ratio through untested. Observed worst deviations are 2.8%
/// (shape, at size 100), 1.2% (scale, at size 500) and 0.003 absolute (ratio).
///
/// The residual is smoothing, not sampling: the raw per-anchor fits agree with
/// the reference to about 1%. The smoother is meant to move a single anchor, and
/// the span was chosen to minimise error against a 40000-permutation curve
/// rather than against any one anchor, so a few percent here is the design
/// working. The tests print every anchor's deviation, so a regression says which
/// size moved.
const SHAPE_TOL: f64 = 0.035;

/// Tolerance for the calibrated gamma scale.
const SCALE_TOL: f64 = 0.02;

/// Tolerance for the gamma mean, `shape * scale`.
const MEAN_TOL: f64 = 0.035;

/// Absolute tolerance for the positive-score ratio.
///
/// Absolute rather than relative: the ratio never leaves roughly `0.49..0.52` on
/// a centred signature, so a relative tolerance of a few percent admits the
/// entire plausible range and would pass against a hardcoded one half.
const RATIO_TOL: f64 = 0.01;

/// Permutations for the calibration parity check.
///
/// The reference fixtures use twenty thousand. Fewer here because the test runs
/// in a debug build.
const CALIBRATION_PERMUTATIONS: usize = 8000;

/////////////
// Helpers //
/////////////

/// Rebuild the fixture signature exactly as the generator does.
///
/// Numerical Recipes LCG, then `x / 2^32 * 6 - 3`. The divisor is a power of
/// two so that step is exact, and the multiply and subtract are one rounding
/// each, which IEEE 754 pins to the same result in both languages.
///
/// ### Returns
///
/// The signature values sorted descending, matching the order the fixture
/// indices refer to.
fn fixture_signature() -> Vec<f64> {
    let mut state = LCG_SEED;
    let mut values: Vec<f64> = Vec::with_capacity(N_GENES);

    for _ in 0..N_GENES {
        state = (1_664_525u64.wrapping_mul(state).wrapping_add(1_013_904_223)) % (1u64 << 32);
        values.push(state as f64 / 4_294_967_296.0 * 6.0 - 3.0);
    }

    values.sort_unstable_by(|a, b| b.total_cmp(a));
    values
}

/// The deterministic positive sample the gamma fitting fixture was built on.
///
/// `(state mod 10000 + 1) / 100`, an integer over a constant, so it is one
/// rounding and identical on both sides.
///
/// ### Returns
///
/// `GAMMA_FIT_N` strictly positive values.
fn fixture_positive_sample() -> Vec<f64> {
    let mut state = LCG_SEED;

    (0..GAMMA_FIT_N)
        .map(|_| {
            state = (1_664_525u64.wrapping_mul(state).wrapping_add(1_013_904_223)) % (1u64 << 32);
            (state % 10_000 + 1) as f64 / 100.0
        })
        .collect()
}

/// A null whose interpolation returns [`FIXTURE_TAIL`] at every gene set size.
///
/// Two anchors carrying identical parameters, so the scoring path runs in full
/// while the tail it sees is pinned to what the fixtures were generated
/// against.
///
/// ### Returns
///
/// The constant null.
fn constant_null() -> BlitzGseaNull {
    BlitzGseaNull {
        anchor_sizes: vec![1.0, N_GENES as f64],
        shape_pos: vec![FIXTURE_TAIL.shape_pos; 2],
        scale_pos: vec![FIXTURE_TAIL.scale_pos; 2],
        shape_neg: vec![FIXTURE_TAIL.shape_neg; 2],
        scale_neg: vec![FIXTURE_TAIL.scale_neg; 2],
        pos_ratio: vec![FIXTURE_TAIL.pos_ratio; 2],
        ks_pos: 1.0,
        ks_neg: 1.0,
        centred: true,
    }
}

/// [`FIXTURE_TAIL`] as the crate's own tail type.
fn fixture_tail() -> BlitzGseaTail {
    BlitzGseaTail {
        shape_pos: FIXTURE_TAIL.shape_pos,
        scale_pos: FIXTURE_TAIL.scale_pos,
        shape_neg: FIXTURE_TAIL.shape_neg,
        scale_neg: FIXTURE_TAIL.scale_neg,
        pos_ratio: FIXTURE_TAIL.pos_ratio,
    }
}

///////////////////////
// Enrichment score //
///////////////////////

/// The core statistic, against `blitzgsea.enrichment_score`.
#[test]
fn test_enrichment_scores_match_reference() {
    let stats = fixture_signature();
    let null = constant_null();
    let params = BlitzGseaParams::default();

    let pathways: Vec<Vec<i32>> = ES_FIXTURES.iter().map(|f| f.indices.to_vec()).collect();
    let res = blitzgsea_score(&stats, &pathways, &null, &params, false).unwrap();

    for (fixture, es) in ES_FIXTURES.iter().zip(res.es.iter()) {
        assert_relative_eq!(*es, fixture.es, max_relative = EXACT_TOL);
    }
}

/// The leading edge, against `blitzgsea.get_leading_edge`.
///
/// A deliberate, exact one-gene disagreement on positively enriched sets. The
/// reference intersects the hits with `range(rmax)`, which is exclusive of the
/// peak and so drops the gene sitting at it. That gene belongs to the leading
/// edge under the standard definition, and `fgsea::calcGseaStat` returns it:
/// on the `strided_50` fixture fgsea gives thirteen genes where the reference
/// gives twelve.
///
/// Asserted as exact equality plus one rather than as a bound, so that this
/// notices if the difference ever stops being that single gene. Negatively
/// enriched sets are compared outright, since the reference's negative branch
/// is inclusive at its end and agrees.
#[test]
fn test_leading_edge_matches_reference_up_to_the_peak_gene() {
    let stats = fixture_signature();
    let null = constant_null();
    let params = BlitzGseaParams::default();

    let pathways: Vec<Vec<i32>> = ES_FIXTURES.iter().map(|f| f.indices.to_vec()).collect();
    let res = blitzgsea_score(&stats, &pathways, &null, &params, false).unwrap();

    for ((fixture, leading), es) in ES_FIXTURES
        .iter()
        .zip(res.leading_edge.iter())
        .zip(res.es.iter())
    {
        let mut ours = leading.clone();
        ours.sort_unstable();

        let name = fixture.name;
        let theirs = fixture.leading_edge;

        for gene in theirs {
            assert!(
                ours.contains(gene),
                "{name}: reference gene {gene} missing from our leading edge"
            );
        }

        let expected = if *es > 0.0 {
            theirs.len() + 1
        } else {
            theirs.len()
        };
        assert_eq!(
            ours.len(),
            expected,
            "{name}: {} genes against the reference's {}",
            ours.len(),
            theirs.len()
        );
    }
}

////////////////////////
// p-value and NES //
////////////////////////

/// The score-to-p-value mapping, across both signs.
///
/// This is the part that was rewritten: the reference's
/// `1 - min(cdf * ratio + 1 - ratio, 1)` is algebraically `ratio * sf`, and the
/// survival function is evaluated directly. Matching here is what says the
/// rewrite is a rewrite and not a change.
#[test]
fn test_pval_and_nes_match_reference() {
    let tail = fixture_tail();

    for fixture in PVAL_FIXTURES {
        let (pval, nes) = pval_and_nes(fixture.es, &tail).unwrap();

        assert_relative_eq!(pval, fixture.pval, max_relative = EXACT_TOL);
        assert_relative_eq!(nes, fixture.nes, max_relative = EXACT_TOL);
    }
}

/// The same mapping reached through the public scoring path rather than
/// directly, so the enrichment score, the interpolation and the tail are all
/// gated together.
#[test]
fn test_scoring_end_to_end_matches_reference() {
    let stats = fixture_signature();
    let null = constant_null();
    let params = BlitzGseaParams::default();

    let pathways: Vec<Vec<i32>> = ES_FIXTURES.iter().map(|f| f.indices.to_vec()).collect();
    let res = blitzgsea_score(&stats, &pathways, &null, &params, false).unwrap();

    for ((fixture, pval), nes) in ES_FIXTURE_PVALS
        .iter()
        .zip(res.pvals.iter())
        .zip(res.nes.iter())
    {
        assert_relative_eq!(*pval, fixture.pval, max_relative = EXACT_TOL);
        assert_relative_eq!(*nes, fixture.nes, max_relative = EXACT_TOL);
    }
}

///////////////////
// Gamma fitting //
///////////////////

/// The gamma MLE, against `scipy.stats.gamma.fit(x, floc=0)`.
#[test]
fn test_gamma_fit_matches_scipy() {
    let sample = fixture_positive_sample();

    let (shape, scale) = fit_gamma_mle(&sample).unwrap();

    assert_relative_eq!(shape, GAMMA_FIT_SHAPE, max_relative = 1e-6);
    assert_relative_eq!(scale, GAMMA_FIT_SCALE, max_relative = 1e-6);
}

/////////////////////////
// Anchor calibration //
/////////////////////////

/// The calibrated gamma parameters, against the reference's per-anchor fits.
///
/// Statistical rather than exact, for the reason given at the top of the file.
/// `symmetric` is forced on so both sides pool the tails into one gamma, which
/// is what the reference's fixture does.
///
/// Behind `large-test`: a full calibration at
/// [`CALIBRATION_PERMUTATIONS`] costs tens of seconds of CPU in a debug build,
/// which is more than a CI job should pay on every push. The deterministic
/// parity tests above are the cheap gates and stay ungated.
#[test]
#[cfg_attr(not(feature = "large-test"), ignore)]
fn test_calibration_matches_reference_within_sampling_error() {
    let stats = fixture_signature();
    let params = BlitzGseaParams {
        permutations: CALIBRATION_PERMUTATIONS,
        symmetric: true,
        ks_test: false,
        ..Default::default()
    };

    let null = calibrate_null(&stats, &params).unwrap();

    let mut worst_shape = 0.0f64;
    let mut worst_scale = 0.0f64;
    let mut worst_ratio = 0.0f64;

    for fixture in ANCHOR_FIXTURES {
        let tail = null.tail_at(fixture.size as f64);

        let shape = ((tail.shape_pos - fixture.shape) / fixture.shape).abs();
        let scale = ((tail.scale_pos - fixture.scale) / fixture.scale).abs();
        let ratio = (tail.pos_ratio - fixture.pos_ratio).abs();
        println!(
            "size {:4}: shape {:+.4} scale {:+.4} ratio {:+.4}",
            fixture.size, shape, scale, ratio
        );

        worst_shape = worst_shape.max(shape);
        worst_scale = worst_scale.max(scale);
        worst_ratio = worst_ratio.max(ratio);
    }

    assert!(
        worst_shape < SHAPE_TOL,
        "worst shape deviation {worst_shape:.4} exceeds {SHAPE_TOL}"
    );
    assert!(
        worst_scale < SCALE_TOL,
        "worst scale deviation {worst_scale:.4} exceeds {SCALE_TOL}"
    );
    assert!(
        worst_ratio < RATIO_TOL,
        "worst ratio deviation {worst_ratio:.4} exceeds {RATIO_TOL}"
    );
}

/// The mean of the fitted gamma has to track the mean of the null scores it was
/// fitted to, whatever the sampling noise.
///
/// Shape and scale are strongly anti-correlated in a gamma fit, so this is the
/// better-conditioned quantity and it catches the two drifting in opposite
/// directions and cancelling.
#[test]
#[cfg_attr(not(feature = "large-test"), ignore)]
fn test_calibration_gamma_means_match_reference() {
    let stats = fixture_signature();
    let params = BlitzGseaParams {
        permutations: CALIBRATION_PERMUTATIONS,
        symmetric: true,
        ks_test: false,
        ..Default::default()
    };

    let null = calibrate_null(&stats, &params).unwrap();

    let mut worst = 0.0f64;
    for fixture in ANCHOR_FIXTURES {
        let tail = null.tail_at(fixture.size as f64);
        let reference = fixture.shape * fixture.scale;
        worst = worst.max(((tail.shape_pos * tail.scale_pos - reference) / reference).abs());
    }

    assert!(
        worst < MEAN_TOL,
        "worst gamma-mean deviation {worst:.4} exceeds {MEAN_TOL}"
    );
}
