//! Parity against the CellPhoneDB v5 statistical method.
//!
//! The means are deterministic and match to rounding. The p-values come from a
//! different RNG, so they are checked against the Monte Carlo error of 1000
//! permutations, and the significance calls must agree away from the
//! threshold.

//!
//! Fixtures in `cpdb_fixtures/` are regenerated by `dev/gen_cpdb_fixtures.py`.

#![cfg(feature = "single-cell")]

use bixverse_rs::prelude::*;
use bixverse_rs::single_cell::sc_analysis::cellphonedb::{
    CellPhoneDbParams, LrInteraction, cellphonedb_statistical,
};
use bixverse_rs::single_cell::sc_data::in_memory_io::InMemorySparseReader;

mod cpdb_fixtures;
use cpdb_fixtures::*;

///////////////
// Constants //
///////////////

/// Expression threshold passed to [CellPhoneDbParams].
const THRESHOLD: f64 = 0.1;
/// Permutation seed. The reference uses a different RNG, so this does not
/// need to match its seed.
const SEED: usize = 42;
/// Relative tolerance on the means, floored at an absolute 1e-6. The reference
/// casts counts to f32 before averaging.
const MEAN_TOL: f64 = 1e-6;
/// Standard errors of Monte Carlo slack allowed between the two p-values.
const MC_Z: f64 = 4.0;
/// Significance cut-off the calls are compared at.
const ALPHA: f64 = 0.05;
/// Reference p-values below this must be significant on our side too.
const CLEAR_HIT: f64 = 0.01;
/// Reference p-values above this must be non-significant on our side too.
const CLEAR_MISS: f64 = 0.2;

/////////////
// Helpers //
/////////////

/// Numerical Recipes LCG, mirroring `dev/gen_cpdb_fixtures.py`.
struct Lcg(u64);

impl Lcg {
    /// Advances the state.
    ///
    /// ### Returns
    ///
    /// The new state, in `0..2^32`.
    fn next(&mut self) -> u64 {
        self.0 = (1664525 * self.0 + 1013904223) % (1 << 32);
        self.0
    }
}

/// The fixture matrix, rebuilt from the LCG exactly as the generator does.
///
/// ### Returns
///
/// CSC over `(cells, genes)`, normalised values in `data_2`.
fn fixture_matrix() -> CompressedSparseData2<u32, f32> {
    let labels: Vec<usize> = CLUSTER_SIZES
        .iter()
        .enumerate()
        .flat_map(|(k, &n)| std::iter::repeat_n(k, n))
        .collect();
    let mut rng = Lcg(LCG_SEED);
    let mut data_2: Vec<f32> = Vec::new();
    let mut indices: Vec<u32> = Vec::new();
    let mut indptr: Vec<u32> = vec![0];
    for g in 0..GENES.len() {
        for (c, &k) in labels.iter().enumerate() {
            let u = rng.next();
            let v = rng.next();
            if (u >> 8) % 1000 < DENSITY[(g * 7 + k * 5) % DENSITY.len()] {
                data_2.push(1.0 + ((v >> 16) % 24) as f32 / 8.0);
                indices.push(c as u32);
            }
        }
        indptr.push(data_2.len() as u32);
    }
    let data: Vec<u32> = data_2.iter().map(|&v| (v * 8.0) as u32).collect();
    CompressedSparseData2::new_csc(
        &data,
        &indices,
        &indptr,
        Some(&data_2),
        (labels.len(), GENES.len()),
    )
}

///////////
// Tests //
///////////

/// Means match the reference to rounding, p-values within Monte Carlo error,
/// and significance calls agree away from the threshold.
#[test]
fn test_cpdb_parity_with_reference() {
    let matrix = fixture_matrix();
    let reader = InMemorySparseReader::new(&matrix, None).expect("reader failed");
    let mut start = 0;
    let clusters: Vec<Vec<usize>> = CLUSTER_SIZES
        .iter()
        .map(|&n| {
            start += n;
            (start - n..start).collect()
        })
        .collect();
    let interactions: Vec<LrInteraction> = FIXTURES
        .iter()
        .map(|f| LrInteraction {
            partner_a: f.partner_a.to_vec(),
            partner_b: f.partner_b.to_vec(),
        })
        .collect();

    let params = CellPhoneDbParams::new(ITERATIONS, THRESHOLD, SEED, None);
    let res = cellphonedb_statistical::<f64, _>(
        &reader,
        &interactions,
        &clusters,
        Some(PAIRS),
        Some(params),
    )
    .expect("cellphonedb_statistical failed");

    let n = ITERATIONS as f64;
    let mut n_tested = 0;
    for (i, f) in FIXTURES.iter().enumerate() {
        for (p, pair) in PAIRS.iter().enumerate() {
            let ctx = format!("{} pair {pair:?}", f.id);
            let got_mean = res.obs.means[(i, p)];
            assert!(
                (got_mean - f.means[p]).abs() <= MEAN_TOL * f.means[p].max(1.0),
                "{ctx}: mean {got_mean} vs {}",
                f.means[p]
            );

            let tested = res.obs.gate[i * PAIRS.len() + p] && got_mean > 0.0;
            if !tested {
                assert_eq!(f.pvals[p], 1.0, "{ctx}: reference tested an untested entry");
                assert_eq!(res.pvals[(i, p)], 1.0, "{ctx}");
                continue;
            }
            n_tested += 1;

            let (got, want) = (res.pvals[(i, p)], f.pvals[p]);
            // both sides are Monte Carlo estimates; pool them so p = 0 on one
            // side does not collapse the standard error
            let pooled = (got + want) / 2.0;
            let tol = MC_Z * (2.0 * pooled * (1.0 - pooled) / n).sqrt() + 1.0 / n;
            assert!((got - want).abs() <= tol, "{ctx}: p {got} vs {want}");
            if want < CLEAR_HIT {
                assert!(got <= ALPHA, "{ctx}: p {got} vs {want}");
            } else if want > CLEAR_MISS {
                assert!(got > ALPHA, "{ctx}: p {got} vs {want}");
            }
        }
    }
    assert!(n_tested > 0, "no entry passed the gate");
}
